### PR TITLE
:sparkles: Add task dashboard report.

### LINKED ISSUE #725: :bug: Fetch task collection limited to 500
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Konveyor version

0.5

### Priority

Blocker

### Current Behavior

GET /tasks limited to 500.  This is consistent with other _Large_ endpoints but causes difficulties for the UI.
Solution:
Add a new _dashboard_ (report) endpoint: `/tasks/report/dashboard`.  
A task dashboard resource is:
- id
- createTime
- createUser
- name
- kind
- addon
-  state
- errors (count)
- application
  - id
  - name
- started
- terminated

 Filters:
- kind
- createUser
- addon
- name
- locator
- state
- application.id
- application.name

### Expected Behavior

_No response_

### How Reproducible

Always (Default)

### Steps To Reproduce

1. Cause more than 500 tasks to be created.
2. UI will error trying to fetch them all.

### Environment

```markdown
- OS:
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by jortel**
Better support succeeded with errors.

closes #725 

needed by: https://github.com/konveyor/tackle2-ui/issues/1997

Example:
GET /tasks/report/dashboard
```
- id: 7
  createUser: admin.noauth
  createTime: 2024-07-15T15:35:53.198405073Z
  name: Daytrader7.1.windup
  kind: analyzer
  addon: analyzer
  state: Succeeded
  application:
    id: 1
    name: Daytrader7
  started: 2024-07-15T15:35:53.514805251Z
  terminated: 2024-07-15T15:39:40.54619695Z
- id: 8
  createTime: 2024-07-15T18:29:25.26836735Z
  name: Daytrader8-
  kind: language-discovery
  addon: language-discovery
  state: Failed
  application:
    id: 2
    name: Daytrader8
  started: 2024-07-15T18:29:25.648121267Z
  terminated: 2024-07-15T18:29:29.798022283Z
  errors: 1
- id: 9
  createTime: 2024-07-15T18:29:25.26883083Z
  name: Daytrader8-
  kind: tech-discovery
  addon: tech-discovery
  state: Failed
  application:
    id: 2
    name: Daytrader8
  started: 2024-07-15T18:29:29.798635671Z
  terminated: 2024-07-15T18:29:32.944556989Z
  errors: 1
```

### CODE REVIEW

File: api/task.go [hunk 1]
```diff
@@ -181,6 +183,7 @@ func (h TaskHandler) List(ctx *gin.Context) {
 	db := h.DB(ctx)
 	db = db.Model(&model.Task{})
 	db = db.Joins("Application")
+	db = db.Joins("Report")
```
Comment (jortel) [inline api/task.go:186]: hint: joining so that /tasks will return the same resources as /tasks/:d.

**Review by mansam — APPROVED** [review]
LGTM
